# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/ko

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: About Jeon Halin
  params:
    description: This is a CV Website About Jeon Halin.
