# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: ./content/ko
  params: {}

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: ./content/en
  params:
    title: About Jeon Halin
    description: This is a CV Website About Jeon Halin


languages:
  ko:
    languageName: 한국어
    weight: 1
  en:
    languageName: English
    weight: 2
