# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/


  ko:
    languageName: 한국어
    languageCode: ko
    contentDir: ./content/ko
    weight: 1
    menu:
      main:
        - identifier: ko-intro
        - identifier: ko-papers
        - identifier: ko-talks
        - identifier: ko-news
        - identifier: ko-experience
        - identifier: ko-projects
        - identifier: ko-teaching

  en:
    languageName: English
    languageCode: en-us
    contentDir: ./content/en
    weight: 2
    menu:
      main:
        - identifier: en-bio
        - identifier: en-papers
        - identifier: en-talks
        - identifier: en-news
        - identifier: en-experience
        - identifier: en-projects
        - identifier: en-teaching
