# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/



languages:
  ko:
    languageName: 한국어
    languageCode: ko
    contentDir: ./content/ko
    weight: 1
    menu:
      main: ["ko-intro", "ko-papers", "ko-talks", "ko-news", "ko-experience", "ko-projects", "ko-teaching"]

  en:
    languageName: English
    languageCode: en-us
    contentDir: ./content/en
    weight: 2
    menu:
      main: ["en-bio", "en-papers", "en-talks", "en-news", "en-experience", "en-projects", "en-teaching"]