# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/ko
  title: 전하린 CV
  params:
    description: 전하린의 CV 웹사이트입니다.
  menu:
    main:
      - name: 소개
        url: /
        weight: 100
#      - name: 논문
#        url: /#papers
#        weight: 11
      - name: 강연
        url: /#talks
        weight: 120
      - name: 뉴스
        url: /#news
        weight: 130
      - name: 경력
        url: experience/
        weight: 200
      - name: 중학교
        url: middle-school/
        weight: 210
      - name: 고등학교
        url: high-school/
        weight: 220
      - name: 대학교
        url: university/
        weight: 230
      - name: 프로젝트
        url: projects/
        weight: 300
#      - name: 교육
#        url: teaching/
#        weight: 40


# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Jeon Halin CV
  params:
    description: This is a CV Website About Jeon Halin
  menu:
    main:
      - name: Bio
        url: /
        weight: 100
#      - name: Papers
#        url: /#papers
#        weight: 11
      - name: Talks
        url: /#talks
        weight: 120
      - name: News
        url: /#news
        weight: 130
      - name: Experience
        url: experience/
        weight: 200
      - name: Middle School
        url: middle-school/
        weight: 210
      - name: High School
        url: high-school/
        weight: 220
      - name: University 
        url: university/
        weight: 230
      - name: Projects
        url: projects/
        weight: 300
#      - name: Teaching
#        url: teaching/
#        weight: 40


languages:
  ko:
    languageName: 한국어
    weight: 1
  en:
    languageName: English
    weight: 2
