# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /
    weight: 100
#  - name: 논문
#    url: /#papers
#    weight: 11
  - name: 강연
    url: /#talks
    weight: 120
  - name: 뉴스
    url: /#news
    weight: 130
  - name: 경력
    url: experience/
    weight: 200
  - name: 프로젝트
    url: projects/
    weight: 300
#  - name: 교육
#    url: teaching/
#    weight: 40
